version: "3"
networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_api_test
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=php_api_test
    networks:
      - application
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        php artisan serve --host=0.0.0.0 --port=8000
